sudo: false

language: node_js

node_js:
  - 10

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - npm run build:all
  - echo $NPM_EMAIL

cache: node_modules

#deploy:
#  provider: npm
#  email: $NPM_EMAIL
#  api_key: $NPM_API_KEY
